[meta]
name        = "Discord Rivalry Ping"
author      = "FabianvZ, Lokulicious"
category    = "Utilities"
version     = "1.2.1"

[script]
dependencies = [ "NadeoServices" ]
optional_dependencies = [ "ChampionMedals", "Discord", "GrindingStats", "WarriorMedals" ]